### ISSUE TITLE
Source Sans Pro isn't applied as a main font family when using XeLaTeX

### ISSUE THREAD

**Issue by Wandmalfarbe** [silkeh/latex-sourcesanspro#1]
When [I use your package with the option `default`](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex#L488) and compile it with XeLaTeX, the main font-family is not Source Sans Pro but the latex default.

<img width="841" alt="screenshot 2017-11-16 16 52 18" src="https://user-images.githubusercontent.com/17237627/32900770-87ea9870-caee-11e7-9a49-9669f9961823.png">

The complete log and LaTeX code can be seen [in this gist](https://gist.github.com/iandol/b6b7667bc6c29abcbfdb7f754f6a012e). The gist is slighly out of date because I now load the package like this `\usepackage[default]{sourcesanspro}`. Unfortunately the issue persists.

---
You can see the original issue [here](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/8).

**Comment by silkeh** [comment]
This seems to be an issue with `polyglossia`, see reutenauer/polyglossia#127 and reutenauer/polyglossia#186.

**Comment by Wandmalfarbe** [comment]
Thank you for the quick help.
