### ISSUE TITLE
Differences in »1« glyph

### ISSUE THREAD

**Issue by SFr682k** [silkeh/latex-sourcesanspro#2]
I am using the the `sourcesanspro` package together with different engines and noted a small difference between the glyph for the number »1« (in both, lining and old style numbers) and the »original« OpenType font files downloaded from the [`adobe-fonts` `source-sans-pro` GitHub repository](https://github.com/adobe-fonts/source-sans-pro) and included using `fontspec`:

![sourcesans1](https://user-images.githubusercontent.com/23553692/34916704-acf8815a-f93c-11e7-9736-520dbc6a2422.png)

This problem occures not only with `pdflatex`, but also with `latex`, `xelatex` and `lualatex`

**Comment by silkeh** [comment]
Thanks for reporting this, and well spotted!

The `sourcesanspro` package loads the font with *proportional* numbers by default (use the `tabular` option to override this), while the font itself uses *tabular* numbers by default.

Note that using the `tabular` option currently causes some `fontspec` warnings, which can be ignored. I will fix this, possibly along with the default behaviour, soon.
