### ISSUE TITLE
Font name of italic fonts

### ISSUE THREAD

**Issue by stone-zeng** [silkeh/latex-sourcesanspro#4]
I have noticed in your repository, the italic font of regular weight is called `SourceSansPro-RegularIt.otf`. In [Adobe's official repo](https://github.com/adobe-fonts/source-sans-pro), however, it is called `SourceSansPro-It.otf`. Do you have some special reasons for this change? Actually, this modification has lead to some difficulties for selecting fonts in LaTeX (I have to use a switch to choose the correct font name).

The same problem also appears in [latex-sourcecodepro](https://github.com/silkeh/latex-sourcecodepro).

Please consider to change them into the same names as in Adobe's release. Thank you!

**Comment by silkeh** [comment]
This change makes the naming more regular (`{weight}` and `{weight}It`). The main font definition, for example, is:

```latex
\setsansfont
	[ UprightFont    = *-\sourcesanspro@regstyle ,
	  ItalicFont     = *-\sourcesanspro@regstyle It ,
	  BoldFont       = *-\sourcesanspro@boldstyle ,
	  BoldItalicFont = *-\sourcesanspro@boldstyle It]
	{SourceSansPro}
```

From your issue it is not clear to me why this would cause issues, but I'd consider a pull request with a clean implementation to change this.
