### ISSUE TITLE
ctan not up to date to version 2.7

### ISSUE THREAD

**Issue by callegar** [silkeh/latex-sourcesanspro#6]
Looks like texlive/ctan still distributes version 2.6 of the package with a 2016 version of the fonts. Would it be possible to push there version 2.7?
As a matter of fact, since 2.7, there has also been a further upstream update to the font (3.006). Would it be possible to take the occasion to get that too?

**Comment by silkeh** [comment]
I have just submitted v2.8 to CTAN. Sorry about the long delay.
